package tunnepaivakirja.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import tunnepaivakirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.04.27 20:33:41 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class TunnetilaTest {



  // Generated by ComTest BEGIN
  /** testVastaaTunnetila42 */
  @Test
  public void testVastaaTunnetila42() {    // Tunnetila: 42
    Tunnetila tun = new Tunnetila(); 
    Tunnetila tun2 = new Tunnetila(); 
    tun2.vastaaTunnetila(1,1,7); 
    tun.vastaaTunnetila(3,1,4); 
    assertEquals("From: Tunnetila line: 47", 1, tun.getpvmNro()); 
    assertEquals("From: Tunnetila line: 48", 1, tun2.getpvmNro()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testVastaaTunnetila63 */
  @Test
  public void testVastaaTunnetila63() {    // Tunnetila: 63
    Tunnetila tunne = new Tunnetila(); 
    tunne.vastaaTunnetila(1,3,"7"); 
    assertEquals("From: Tunnetila line: 66", 7, tunne.voimakkuus); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi131 */
  @Test
  public void testRekisteroi131() {    // Tunnetila: 131
    Tunnetila tunne1 = new Tunnetila(); 
    assertEquals("From: Tunnetila line: 133", 0, tunne1.getTunnusNro()); 
    tunne1.rekisteroi(); 
    Tunnetila tunne2 = new Tunnetila(); 
    tunne2.rekisteroi(); 
    int n1 = tunne1.getTunnusNro(); 
    int n2 = tunne2.getTunnusNro(); 
    assertEquals("From: Tunnetila line: 139", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetTunnusNro152 */
  @Test
  public void testGetTunnusNro152() {    // Tunnetila: 152
    Tunnetila tunne = new Tunnetila(); 
    assertEquals("From: Tunnetila line: 154", 0, tunne.getTunnusNro()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSetTunnusNro165 */
  @Test
  public void testSetTunnusNro165() {    // Tunnetila: 165
    Tunnetila tunne = new Tunnetila(); 
    tunne.setTunnusNro(4); 
    assertEquals("From: Tunnetila line: 168", 4, tunne.getTunnusNro()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetpvmNro180 */
  @Test
  public void testGetpvmNro180() {    // Tunnetila: 180
    Tunnetila tunne1 = new Tunnetila(); 
    tunne1.vastaaTunnetila(2,3,4); 
    Tunnetila tunne2 = new Tunnetila(); 
    tunne2.vastaaTunnetila(3,4,5); 
    assertEquals("From: Tunnetila line: 185", 3, tunne1.getpvmNro()); 
    assertEquals("From: Tunnetila line: 186", 4, tunne2.getpvmNro()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetVoimakkuus197 */
  @Test
  public void testGetVoimakkuus197() {    // Tunnetila: 197
    Tunnetila tunne1 = new Tunnetila(); 
    tunne1.vastaaTunnetila(2,3,4); 
    Tunnetila tunne2 = new Tunnetila(); 
    tunne2.vastaaTunnetila(3,4,5); 
    assertEquals("From: Tunnetila line: 202", "4", tunne1.getVoimakkuus()); 
    assertEquals("From: Tunnetila line: 203", "5", tunne2.getVoimakkuus()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString214 */
  @Test
  public void testToString214() {    // Tunnetila: 214
    Tunnetila tunne = new Tunnetila(); 
    tunne.parse("   1  |  1   | 7"); 
    assertEquals("From: Tunnetila line: 217", true, tunne.toString().startsWith("1|1|7|"));  // on enemmäkin kuin 3 kenttää, siksi loppu |
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse229 */
  @Test
  public void testParse229() {    // Tunnetila: 229
    Tunnetila tunne = new Tunnetila(); 
    tunne.parse("   1  |  1   | 7"); 
    assertEquals("From: Tunnetila line: 232", 1, tunne.getTunnusNro()); 
    assertEquals("From: Tunnetila line: 233", true, tunne.toString().startsWith("1|1|7|"));  // on enemmäkin kuin 3 kenttää, siksi loppu |
    tunne.rekisteroi(); 
    int n = tunne.getTunnusNro(); 
    tunne.parse(""+(n+20));  // Otetaan merkkijonosta vain tunnusnumero
    tunne.rekisteroi();  // ja tarkistetaan että seuraavalla kertaa tulee yhtä isompi
    assertEquals("From: Tunnetila line: 239", n+20+1, tunne.getTunnusNro()); 
  } // Generated by ComTest END
}