package test.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import test.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.05.03 23:53:43 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class AllTestsTest {
    //
}